---
language: node_js
node_js:
  - "6"

sudo: false

cache:
  yarn: true

env:
  # we recommend testing LTS's and latest stable release (bonus points to beta/canary)
  - EMBER_TRY_SCENARIO=ember-lts-2.12
  - EMBER_TRY_SCENARIO=ember-lts-2.16
  - EMBER_TRY_SCENARIO=ember-lts-2.18
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - phantomjs --version

install:
  - yarn install --no-lockfile

script:
  - yarn lint:js
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup
  - yarn test:node

before_deploy:
  - yarn global add auto-dist-tag
  - auto-dist-tag --write

deploy:
  provider: npm
  email: stefan.penner+ember-cli@gmail.com
  api_key:
    secure: OrnTvkC2eejgwTnOFs21kmojEM5Tky1JwpWoMgks9dOmQxp4ucpHQyv748FZkQ8NyOExduqs966ko4W/1yZ6wJfNatNZa1I49qCgYXjM3FJI0gxan/Y6KVjt8QQEsR5XsPN5xALh2D65h3WUOwsTQLcCQX9yR0fahj53cDcrmws=
  on:
    tags: true
    repo: ember-cli/ember-cli-htmlbars-inline-precompile
